# Generated by Django 2.1.7 on 2019-03-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190320_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='who',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='snack',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Store'),
        ),
    ]
