# Generated by Django 2.1.7 on 2019-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_snack_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
