# Generated by Django 2.1.7 on 2019-04-10 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0007_auto_20190410_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='author',
        ),
        migrations.AddField(
            model_name='snack',
            name='snack_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
