# Generated by Django 2.1.7 on 2019-04-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20190410_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
